version: '3.8'

services:
  database:
    image: mysql:5.7
    command: --lower_case_table_names=1
    platform: linux/amd64
    restart: always
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: musi
      MYSQL_ROOT_PASSWORD: rlaekdud
    volumes:
      - ./db:/var/lib/mysql
      - - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - docker_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kimdayeong/musi
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - database
    container_name: musi-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/musi?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rlaekdud
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge