version: '3.8'

services:
  database:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: musi
      MYSQL_ROOT_PASSWORD: rlaekdud
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - docker_network

  app:
    build:
      context: src/main
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - database
    container_name: musi-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/musi?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge
